### ISSUE TITLE
space-cli generate remote services does not work properly

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#1126]
Here's the yaml file that I am applying:

```yaml
api: /v1/config/projects/{project}/remote-service/service/{id}
meta:
  id: myapp
  project: myproject
spec:
  endpoints:
  - add:
      method: POST
      path: /
  url: http://localhost:8080
type: remote-services
```

However, after applying, when I open the `config.yaml` file of Space Cloud, it has the following config related to remote services:

```yaml
    remoteServices:
      externalServices:
        myapp:
          endpoints: null
          id: myapp
          url: http://localhost:8080
``` 

Endpoints are empty. However, endpoints should have been present.
