### ISSUE TITLE
Make a DockerCompose file for using SpaceCloud

### ISSUE THREAD

**Issue by cellerich** [spaceuptech/space-cloud#1253]
### Describe the bug
Tried to setup Space Cloud with docker-compose. Ended up with an old version.
Latest version on docker hub seems to be v0.15.x

### Expected behaviour
Have the newest version available

### Steps to reproduce
Here is my `docker-compose.yaml`:

```yaml 
services:
  space-cloud:
    image: spaceuptech/space-cloud
    container_name: spacecloud
    ports:
    - "4122:4122"
    - "4126:4126"
    depends_on:
    - "postgres"
    restart: always
    environment:
      ## The DEV environment lets you use Mission Control (Admin UI) without login
      ## Change the dev mode to false if you want a login to your Mission Control UI
      DEV: "true"
      ## Uncomment next lines to change the login credentials of Mission Control UI
      # ADMIN_USER: "admin"
      # ADMIN_PASS: "123"
      # ADMIN_SECRET: "some-secret" # This is the JWT secret used for login authentication in Mission Control
  postgres:
    image: postgres
    container_name: postgres_db
    volumes:
    - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
    - db-data:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
    restart: always
  
volumes:
  db-data:
``` 

### Your environment
- Space Cloud version: v0.19.1
- OS: windows (on WSL1 - Ubuntu
- Kubernetes or Docker: Docker version 19.03.11
- The client api version (if applicable): v19.0.1
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍
