### ISSUE TITLE
How to control that only partial fields are allowed to be updated?

### ISSUE THREAD

**Issue by bysir-zl** [spaceuptech/space-cloud#146]
The title is all, Thank you for your help.

**Comment by YourTechBud** [comment]
Thats a great question!! If i understand this question, you want to prevent the client from updating certain columns?

Assuming that's the case and the field / column you want to protect is named `protectMe`, you can have a `match` rule something like this:
```yaml
rules:
  update:
    rule: match
    eval: ==
    type: bool
    f1: utils.exist(args.update.$set.protectMe)
    f2: true
```

the solution above is not documented I guess. The `utils.exist()` function seems to be a well kept secret. @Jayesh333 we should get that done

This will protect you against all `set` operations. The client still be able to unset it. Thats a security threat. Normally you wouldn't wanna keep protected data in a collection/table which the user has access to. Can you keep it in a separate table where only an `admin` role or the backend functions can access it? This is what we do. A lil more about your use case would help me give a more accurate answer.

@Jayesh333 another better way of solving this would be introducing wildcards to rules. So basically the new rule would look like this:

> **Note:** this is a proposal and the code below hasn't been implemented

```yaml
rules:
  update:
    rule: match
    eval: ==
    type: bool
    f1: utils.exist(args.update.*.protectMe)
    f2: true
```
The above config would prevent any kind of update whatsoever!

**Comment by akshayjj1997** [comment]
@YourTechBud what are wildcards to rules?

**Comment by YourTechBud** [comment]
You see the '*'? Thats a wild card. It can take the value of any other string so matching becomes a lot easier.

**Comment by 8byr0** [comment]
As this issue is related to user authentication, it would be good to have a default admin field in config.yaml. Something like this:
```
auth:
    email:
      enabled: true
      admin:
            id: my-email@fai.com
            pass: MyLongRand0mPassw0rd
```

**Comment by YourTechBud** [comment]
@8byr0 You can do this instead with what we have already implemented
```yaml
rules:
  update:
    rule: match
    eval: ==
    type: string
    f1: args.auth.role
    f2: admin
```

Instead of creating a default admin we can have a data explorer to add users from a ui? What say?
