### ISSUE TITLE
Can security rules provide a global default option?  I have more than 100 tables. I don't want to write 100 rules.  ...

### ISSUE THREAD

**Issue by hyingreborn** [spaceuptech/space-cloud#167]
like this:
```
collections: 
  default:
    isRealtimeEnabled: false
    rules:
      create:
              rule: allow
            read:
              rule: allow
            update:
              rule: allow
            delete:
              rule: allow
  todos:
    isRealtimeEnabled: true
    rules:
      create:
              rule: authenticated
            read:
              rule: authenticated
            update:
              rule: allow
            delete:
              rule: allow
  ...
```
