### ISSUE TITLE
Ability to put raw MongoDB where query in the mongo client sdk !

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#97]
We are already sending out the where clause as a MongoDB query to the backend. Why not let the user put the raw query directly?

I know this is a request for the client libraries. But lets put it here to keep track. The updates of it being done on individual clients can be done here.

**Comment by ledex** [comment]
One question to this issue: Should there be a 'raw'-rule? Something like 
```
...
users:
          isRealtimeEnabled: false
          rules:
            create:
              rule: ...
            read:
              rule: ...
            update:
              rule: ...
            delete:
              rule: ...
            raw:
              rule: ...
...
```
